import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Personal Knowledge Hub",
	description: "Generated by create next app",
	referrer: "no-referrer",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${inter.className} bg-white w-screen h-screen overflow-x-hidden`}>{children}</body>
		</html>
	);
}
